---
version: '2'
services:
  yocto:
    build:
      context: .
      dockerfile: Dockerfile
    image: 132335/yocto-builder
    volumes:
      - ./shared:/home/build/shared
      - ~/.netrc:/home/build/.netrc:ro
